---
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 3, fig.align='center')
```

John Hendley & Randy Nguyen \

STA 6375 

\begin{center}
Homework 3
\end{center}

## Question 1

a.
```{r, indent = "    ", message = FALSE}
library("tidyverse")

df <- expand.grid("x" = 1:10, "y" = 1:10) 
ggplot(df, aes(x, y)) +
  geom_point() +
  theme_minimal()
```

b.
```{r, indent = "    ", message = FALSE}
ggplot(df, aes(x, y)) +
  geom_point() +
  theme_minimal() +
  coord_equal()
```
  
c.
```{r, indent = "    ", message = FALSE}
set.seed(1)
fuzz <- rnorm(nrow(df))
ggplot(df, aes(x, y, fill = fuzz)) +
  theme_minimal() +
  geom_tile()
```
  
d.
```{r, indent = "    ", message = FALSE}
set.seed(1)
fuzz <- rnorm(nrow(df))
ggplot(df, aes(x, y, fill = fuzz)) +
  theme_minimal() +
  geom_tile() +
  theme(legend.position = "none") +
  coord_equal()
```
  
e.
```{r, indent = "    ", message = FALSE}
set.seed(1)
fuzz <- rnorm(nrow(df))
ggplot(df, aes(x, y, fill = fuzz)) +
  theme_bw() +
  geom_tile() +
  coord_equal() +
  theme(legend.position = "none") +
  scale_fill_distiller(palette = "Greys")
```
  
f.
```{r, indent = "    ", message = FALSE}
set.seed(1)
fuzz <- rnorm(nrow(df))
ggplot(df, aes(x, y, fill = fuzz)) +
  geom_tile() +
  coord_equal() +
  scale_fill_distiller(palette = "Greys") +
  ylab(NULL) +
  xlab(NULL) +
  theme_void() +
  theme(legend.position = "none")
```
  
g.
```{r, indent = "    ", message = FALSE}
x <- seq(0, 1, 1e-4)
fx <- sin(2*pi*x)
sine <- data.frame("x" = x, "y" = fx)
ggplot(sine, aes(x, fx)) +
  theme_minimal() +
  geom_line()
```
  
h.
```{r, indent = "    ", message = FALSE}
x <- seq(0, 1, 1e-4)
fx <- sin(2*pi*x)
sine <- data.frame("x" = x, "y" = fx)
ggplot(sine, aes(x, fx)) +
  theme_minimal() +
  geom_ribbon(aes(ymin = fx - 0.2125, ymax = fx + 0.2125), fill = "grey50", alpha = 0.7) +
  geom_line(color = "green")
```

i.
```{r, indent = "    ", message = FALSE, fig.width = 3}
x <- 
y <- c()
for (i in 0:10) {
  x <- c(x, cos(i*pi/5))
  y <- c(y, sin(i*pi/5))
}

decagon <- data.frame(x, y)
ggplot(decagon, aes(x, y)) +
  geom_point() +
  geom_path() +
  theme_minimal()

```


j.
```{r, indent = "    ", message = FALSE}
set.seed(1)
df <- data.frame(x = rnorm(1e3, mean = 3, sd = 2))
ggplot(df, aes(x)) +
  geom_density() +
  stat_function(fun = dnorm, args = list(mean = 3, sd = 2), color = "red") +
  geom_vline(xintercept = 8, color = "red", linetype = "twodash", size = 1) +
  theme_minimal()
```

## Question 2

a. 
```{r spectral decomposition (eigendecompostion), indent = "    ", message = FALSE}
A <- matrix(c(
  -1, 3, 1,
  -7, 9, 1,
  -2, 3, 4),
  nrow = 3, byrow = TRUE)

r <- eigen(A)
(V <- r$vector)
(lam <- r$values)
Lambda <- diag(lam, nrow = 3, ncol = 3)

V %*% Lambda %*% solve(V)
```


b.
```{r spectral decomposition of real symmetric matrices, indent = "    "}
A <- matrix(c(
  10, 2, -6,
  2, 7, 0,
  -6, 0, 2),
  nrow = 3, byrow = TRUE)

r <- eigen(A)
V <- r$vector
lam <- r$values
Lambda <- diag(lam, nrow = 3, ncol = 3)

# V is orthogonal
zapsmall(crossprod(V))

zapsmall(V %*% Lambda %*% t(V))
```


c.
```{r singular value decompostion (svd), indent = "    "}
A <- matrix(c(
  1, 5, 6,
  2, 6, 8,
  3, 7, 10,
  4, 8, 12),
  nrow = 4, byrow = TRUE)

s <- svd(A, nu = 4)

s$u

# s$u is orthogonal
zapsmall(s$u %*% t(s$u))

s$v

# s$v is orthogonal
zapsmall(s$v %*% t(s$v))

(zapsmall(D <- diag(s$d, nrow = dim(s$u)[1], ncol = dim(s$v)[2])))

s$u %*% D %*% t(V)
```


d.
```{r just testing the example given, indent = "    "}
(A <- matrix(1:4, nrow = 2)) # A is invertible

(elu <- Matrix::expand(Matrix::lu(A)))

with(elu, P %*% L %*% U)
```


e.
```{r Cholesky decomposition, indent = "    "}
A <- matrix(c(
  4, 2, 1,
  2, 4, 2,
  1, 2, 4),
  nrow = 3, byrow = TRUE)

# A is a square 3x3 matrix
# A is a symmetric matrix positive definite matrix since
# the entries are positive and a_{ij} = a_{ji} for all i and j

(U <- chol(A))

# U is orthogonal
crossprod(U)
```

f.
```{r QR decomposition, indent = "    "}
A <- matrix(c(
  1, 3, 2,
  3, 0, 0,
  0, 1, 3,
  0, 1, 0),
  nrow = 4, byrow = TRUE)

(U <- qr.R(qr(A)))

(Q <- qr.Q(qr(A)))

# Q is orthogonal 
zapsmall(crossprod(Q))

zapsmall(Q %*% U)
```